### ISSUE TITLE
预览图如果地址错误，大图地址正确。会造成大图显示不出。

### ISSUE THREAD

**Issue by docallsama** [MSS0306/MSSBrowse#1]
因为smallImageView没有frame

**Comment by mdongsheng** [comment]
@docallsama 是的，但这是个问题，我在competed block中加重新计算了一下， 不过还是没有smallImageView，所以， 向右滑动的时候是可以的，但是向左滑回来就不行了。

**Comment by mdongsheng** [comment]
@MSS0306 我提个PR可以吧？

**Comment by MSS0306** [comment]
问题已修复
